Add React Routers
techEmprez/math-magician pull request #5
Opened 2022-09-16 22:41 UTC by techEmprez

The following took place:

- Used React Router.
- Used styles in a React app.
- Created a website consisting of 3 pages: Home, Calculator, and Quote

2022-09-16 23:22 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @techEmprez 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used react router
✔️ Good commit history
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 23:22 UTC, codepantha commented on src/components/Header.js
> +
- [ ] There seems to be a problem with this import right here as the name of the file is `calculator.js` and not `Calculator.js`. Please modify the import to match the actual file name in order to get rid of the error below 👇 
![image](https://user-images.githubusercontent.com/46839548/190829613-87946dc8-6215-49d1-ad7e-d8bfc45ecd0a.png)

2022-09-16 23:22 UTC, codepantha commented on src/components/Quote.js
> +  }}
- [ ] It is not good practice to have your styling right here in the JSX. You can create a Quote.css file or simply write the styling in the App.css file instead 👍

2022-09-17 09:32 UTC, Rustamxon7 approved these changes
## Hello @techEmprez 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-17 10:07 UTC, merged